---

plugins:
  - flowtype
  - jest
  - babel
  - prettier

env:
  node: true
  jest/globals: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'
  - 'prettier'

rules:
  no-console: 0
  prettier/prettier: 'error'
